version: "3.4"
services:
  # https://hub.docker.com/_/mongo
  mongodb:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"
      MONGO_INITDB_DATABASE: "${MONGODB_DB}"
    volumes:
      - mongodata:/data/db
    network_mode: host
    # networks:
    #   - mongonet
  # https://hub.docker.com/_/mongo-express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASS}"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}:${MONGODB_PORT}"
    # networks:
    #   - mongonet
    network_mode: host
  # node-web:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   links:
  #     - mongodb
  #   volumes:
  #     - /app/node_modules
  #     - ./:/app
  #   ports:
  #     - "4001:4001"
  #   networks:
  #     - mongonet
  #   environment:
  #     MONGODB_USER: ${MONGODB_USER}
  #     MONGODB_PASS: ${MONGODB_PASS}
  #     MONGODB_HOST: ${MONGODB_HOST}
  #     MONGODB_DB: ${MONGODB_DB}
  #     FETCH_URL: ${FETCH_URL}
  #     CONTRACT_ACCOUNT_ID: ${CONTRACT_ACCOUNT_ID}
  #     NEAR_DB_CONNECTION: ${NEAR_DB_CONNECTION}
  #     NETWORK_ID: ${NETWORK_ID}
  #     NODE_URL: ${NODE_URL}
# networks:
#   mongonet:
#     driver: bridge

volumes:
  mongodata:
